### ISSUE TITLE
size of kaggle/rstats

### ISSUE THREAD

**Issue by nyxee** [Kaggle/docker-rstats#12]
I've been running `docker run --rm -it kaggle/rstats` for a two days now (internet is slightly slow)  but i'e got all the parts bt there's a file **f0b24ff7f2aa** that is currently at **6GB** and doesnt show how much is left. 

can someone please inform me on the maximum size of that file please/

**Comment by sebbov** [comment]
Sorry to hear that is so painful.  This container is very large as it includes all cran packages.  That layer is 7.359GB large, so you are almost there :).
