### ISSUE TITLE
resuming docker downloads

### ISSUE THREAD

**Issue by nyxee** [Kaggle/docker-rstats#13]
is there any way of resuming `ocker run --rm -it kaggle/rstats`on connection failure...

OR, can our good providers help us with a better way of downloading the files from here bit by bit. some of us have extremely spotty connections. my download failed after i had finished downloading about 10GB+. had to think about either starting ove or giving up on this.

**Comment by sebbov** [comment]
Docker has some provisions to resume failed downloads, but there seem to be lingering issues that cause it to not always work [*]. I suggest to use the latest docker version you can use in your environment, and if that still fails file an issue for it at https://github.com/moby/moby/issues/new (if you end up doing that, thanks for letting us know the link to the issue so we can follow along).

[*] Some refs:
- https://github.com/moby/moby/issues/25866
- https://github.com/moby/moby/issues/26146
- https://github.com/moby/moby/pull/28348
