### ISSUE TITLE
Issue installing autoxgboost

### ISSUE THREAD

**Issue by Cdk29** [Kaggle/docker-rstats#135]
Hi,
I was trying to install the following package from github : https://github.com/ja-thomas/autoxgboost

It is not a CRAN package, but the build does not move so much. Anyway I run into the following problem :

`devtools::install_github("ja-thomas/autoxgboost", dependencies = TRUE)`

> Installing 11 packages: digest, R6, waldo, testthat, generics, data.table, RcppArmadillo, cmaes, DiceKriging, mlrCPO, mlrMBO
> 
> Installing packages into ‘/usr/local/lib/R/site-library’
> (as ‘lib’ is unspecified)
> 
> Error: Failed to install 'autoxgboost' from GitHub:
>   (converted from warning) installation of package ‘R6’ had non-zero exit status
> Traceback:
> 
> 1. devtools::install_github("ja-thomas/autoxgboost", dependencies = TRUE)
> 2. pkgbuild::with_build_tools({
>  .     ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
>  .         rlang::warn))
>  .     {
>  .         remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
>  .             auth_token = auth_token, host = host)
>  .         install_remotes(remotes, auth_token = auth_token, host = host, 
>  .             dependencies = dependencies, upgrade = upgrade, force = force, 
>  .             quiet = quiet, build = build, build_opts = build_opts, 
>  .             build_manual = build_manual, build_vignettes = build_vignettes, 
>  .             repos = repos, type = type, ...)
>  .     }
>  . }, required = FALSE)
> 3. install_remotes(remotes, auth_token = auth_token, host = host, 
>  .     dependencies = dependencies, upgrade = upgrade, force = force, 
>  .     quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
>  .     build_vignettes = build_vignettes, repos = repos, type = type, 
>  .     ...)
> 4. tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
>  .     stop(remote_install_error(remotes[[i]], e))
>  . })
> 5. tryCatchList(expr, classes, parentenv, handlers)
> 6. tryCatchOne(expr, names, parentenv, handlers[[1L]])
> 7. value[[3L]](cond)
> 

And : 

`install.packages("R6", dependencies = TRUE, verbose = TRUE)`

> 
> Installing package into ‘/usr/local/lib/R/site-library’
> (as ‘lib’ is unspecified)
> 
> system (cmd0): /usr/local/lib/R/bin/R CMD INSTALL
> 
> foundpkgs: R6, /tmp/RtmpNMSWAV/downloaded_packages/R6_2.5.0.tar.gz
> 
> files: /tmp/RtmpNMSWAV/downloaded_packages/R6_2.5.0.tar.gz
> 
> Warning message in install.packages("R6", dependencies = TRUE, verbose = TRUE):
> “installation of package ‘R6’ had non-zero exit status”

I am a bit surprised by the dryness of the R error message which does not say a lot about this.
Do you see a way to solve this ?

**Comment by Philmod** [comment]
Hi, I suggest to use the `keep_outputs` option to get more details about the failure: 

![Screen Shot 2021-01-21 at 3 08 27 PM](https://user-images.githubusercontent.com/818310/105406557-941fdd80-5bfa-11eb-85f3-f14bf166686c.png)

R6 seems to be installed already:

![Screen Shot 2021-01-21 at 3 11 02 PM](https://user-images.githubusercontent.com/818310/105406809-ed880c80-5bfa-11eb-9ce6-d95b1d85a946.png)

As for autoxgboost, it seems like one dependency fails to install.
