### ISSUE TITLE
Install fastai Library in GPU and CPU Kernels

### ISSUE THREAD

**Issue by Gayathri-Nagarajan** [Kaggle/docker-rstats#145]
Hi Team Kaggle

Please  install this library for both GPU and CPU kernels:
https://github.com/Kaggle/docker-rstats/blob/master/Dockerfile
https://github.com/Kaggle/docker-rstats/blob/master/gpu.Dockerfile

Thanks to Turgut who published the notebook on how to use fastai in R for [image classification](https://www.kaggle.com/henry090/work-with-fast-ai-from-r/comments#1139746)

Iam unable to use it for my learning and submission in competition because its not part of your kernels.

Please acknowledge and help adding the same asap

Regards
Gayathri

**Comment by Cdk29** [comment]
I go agree with this feature request.

**Comment by calderjo** [comment]
old request, you're welcome to reopen or even contribute via a PR.
