### ISSUE TITLE
Update R environment

### ISSUE THREAD

**Issue by jweinflash** [Kaggle/docker-rstats#15]
Would it be possible to update the R kernel environment? I was looking to use the `sf` package (which is on CRAN), but noticed that it's not available in the kernel.

![image](https://user-images.githubusercontent.com/8573201/29669105-629c076e-88b0-11e7-9902-4e52e443da45.png)

**Comment by sebbov** [comment]
Hi Josh,

We went ahead and added that.  It is available on kaggle.com as of now.

Best,
-seb.
