### ISSUE TITLE
Install package daggity and ggdag

### ISSUE THREAD

**Issue by lsun20** [Kaggle/docker-rstats#159]
Would it be possible to add 

https://cran.r-project.org/web/packages/dagitty/index.html
https://cran.r-project.org/web/packages/ggdag/index.html

These packages are used often in causal inference research.  Thanks so much!

**Comment by Philmod** [comment]
They seem installed: 
- https://github.com/Kaggle/docker-rcran/blob/main/packages_users#L570
- https://github.com/Kaggle/docker-rcran/blob/main/packages_users#L817
