### ISSUE TITLE
update package "mlr3verse"

### ISSUE THREAD

**Issue by GeoEv** [Kaggle/docker-rstats#163]
Hi, I tried to update the following package on kaggle with the command:

devtools :: update_packages ("mlr3verse", upgrade = "always", dependencies = TRUE)

Unfortunately it doesn't work. Can you help me please?

The packages on Kaggle are very old: 

> mlr3verse    (0.1.1  -> 0.2.1 ) [CRAN]
> lgr          (0.3.4  -> 0.4.2 ) [CRAN]
> mlr3misc     (0.2.0  -> 0.9.1 ) [CRAN]
> paradox      (0.2.0  -> 0.7.1 ) [CRAN]
> future.apply (1.5.0  -> 1.7.0 ) [CRAN]
> mlr3measures (0.1.3  -> 0.3.1 ) [CRAN]
> parallelly   (NA     -> 1.25.0) [CRAN]
> palmerpen... (NA     -> 0.1.0 ) [CRAN]
> future       (1.17.0 -> 1.21.0) [CRAN]
> globals      (0.12.5 -> 0.14.0) [CRAN]
> clue         (0.3-57 -> 0.3-59) [CRAN]
> mlr3         (0.2.0  -> 0.11.0) [CRAN]
> bbotk        (NA     -> 0.3.2 ) [CRAN]
> mlr3pipel... (0.1.3  -> 0.3.4 ) [CRAN]
> distr6       (NA     -> 1.5.2 ) [CRAN]
> R62S3        (NA     -> 1.4.1 ) [CRAN]
> set6         (NA     -> 0.2.1 ) [CRAN]
> rlang        (0.4.10 -> 0.4.11) [CRAN]
> tibble       (3.1.1  -> 3.1.2 ) [CRAN]
> ellipsis     (0.3.1  -> 0.3.2 ) [CRAN]
> fansi        (0.4.2  -> 0.5.0 ) [CRAN]
> pillar       (1.6.0  -> 1.6.1 ) [CRAN]
> vctrs        (0.3.7  -> 0.3.8 ) [CRAN]
> colorspace   (2.0-0  -> 2.0-1 ) [CRAN]
> cli          (2.4.0  -> 2.5.0 ) [CRAN]
> mlr3cluster  (NA     -> 0.1.1 ) [CRAN]
> mlr3data     (NA     -> 0.3.1 ) [CRAN]
> mlr3filters  (0.2.0  -> 0.4.1 ) [CRAN]
> mlr3fselect  (NA     -> 0.5.1 ) [CRAN]
> mlr3learners (0.2.0  -> 0.4.5 ) [CRAN]
> mlr3proba    (NA     -> 0.4.0 ) [CRAN]
> mlr3tuning   (0.1.2  -> 0.8.0 ) [CRAN]
> mlr3viz      (0.1.1  -> 0.5.3 ) [CRAN]

**Comment by Philmod** [comment]
The `0.2.1` version of `mlr3verse` is now installed.

Best,
Philippe
