### ISSUE TITLE
torch library update

### ISSUE THREAD

**Issue by issactoast** [Kaggle/docker-rstats#177]
To whom may it concern,

Hi, I am using torch package on kaggle notebook but I found that the installed version is little behind.

packageVersion("torch")

shows that the installed version is v0.3.0 but the latest version is 0.6.0. Could you update the torch package on the docker file?

Sincerely,
Issac

**Comment by Philmod** [comment]
Hi @issactoast,

We are working on it, but there are a lot of dependencies we have to upgrade first (including CUDA), so it may take some time.

Best,
Philippe

**Comment by Philmod** [comment]
The version `0.7.2` is now installed.

Best,
Philippe
