### ISSUE TITLE
R: Treesnip package is missing.

### ISSUE THREAD

**Issue by nipnipj** [Kaggle/docker-rstats#185]
Please, add `treesnip` package (https://curso-r.github.io/treesnip/) to kaggle notebooks.

**Comment by nipnipj** [comment]
With `treesnip` I can also use `catboost`. I think this is worth mentioning, since when I install `treesnip` manually into a kaggle kernel, only xgboost works.

**Comment by Philmod** [comment]
Hi! This package doesn't seem to be available in Rcran unfortunately.

But you can install it in your notebooks: `remotes::install_github("curso-r/treesnip")`

Best,
Philippe

**Comment by jrosell** [comment]
I think this should work:
remotes::install_github("curso-r/treesnip", lib = "/kaggle/working")
