### ISSUE TITLE
R error.

### ISSUE THREAD

**Issue by nipnipj** [Kaggle/docker-rstats#192]
Today I'm facing the following error when using `reticulate`. This did not happen just yesterday.
### Describe your issue.

Error when importing `sklearn.mixture`

### Reproducing Code Example

```python
import("sklearn.mixture")

```

### Error message

```
Error in py_module_import(module, convert = convert): ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /root/.local/share/r-miniconda/envs/r-reticulate/lib/python3.8/site-packages/scipy/optimize/_highs/_highs_wrapper.cpython-38-x86_64-linux-gnu.so)

Traceback:

1. import("sklearn.mixture")
2. py_module_import(module, convert = convert)
```

**Comment by calderjo** [comment]
this seems to be an old bug with little context, please reopen if you still find the same issue
