### ISSUE TITLE
`naryn` package

### ISSUE THREAD

**Issue by aviezerl** [Kaggle/docker-rstats#195]
Hi, 

Please add the `naryn` R package. It is a toolkit for medical records data analysis. It implements an efficient data structure for storing and querying medical records, which can be useful in many competitions. 

It is avaliable on CRAN but not on the kaggle notebooks:

https://cran.r-project.org/web/packages/naryn/index.html

Thank you very much

**Comment by Philmod** [comment]
Hi! Have you considered installing this package in your notebook?

![Screenshot 2023-05-30 at 13 04 15](https://github.com/Kaggle/docker-rstats/assets/818310/203d547a-0c8f-4325-978b-3ffeeeaf7e03)

**Comment by aviezerl** [comment]
I am happy to see that naryn is now available. Back when this issue was opened, the cran image did not include it. Thank you very much!
