### ISSUE TITLE
cmdstanr

### ISSUE THREAD

**Issue by nipnipj** [Kaggle/docker-rstats#198]
Is it possible to add `cmdstanr`? if yes what would be the path (`set_cmdstan_path("~/CMDSTAN")`) to it?

**Comment by Philmod** [comment]
Hey!
I can't find this package on rcran?

**Comment by nipnipj** [comment]
I guess it is not there yet.
https://mc-stan.org/cmdstanr/

**Comment by Philmod** [comment]
Feel free to reopen this bug when the package is available in rcran.
