### ISSUE TITLE
Upgrade h2o package

### ISSUE THREAD

**Issue by KobaKhit** [Kaggle/docker-rstats#2]
It looks like the r docker image is using an older version of h2o. When using the `h2o.deeplearning()`function it produces an error

```
label: unnamed-chunk-5
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.2) (7u91-2.6.2-1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
Quitting from lines 49-91 (script.Rmd) 
Error: 
  unexpected argument "data", is this legacy code? Try ?h2o.shim

Execution halted
```

Using `h2o.randomForest()` works fine. Below is the code I am running in Kaggle RMarkdown Notebook with data already read in:
```
library(h2o)
## start a local cluster
localH2O = h2o.init(max_mem_size = '6g', # use 6GB of RAM of 8GB available on Kaggle
                    nthreads = -1) # use all CPUs (8 on my personal computer :3)
               
## import MNIST data as H2O
train_h2o = as.h2o(localH2O,train)
test_h2o = as.h2o(localH2O,test)

## set timer
s <- proc.time()

## train model
model =
  h2o.deeplearning(x = 2:785,  # column numbers for predictors
                   y = 1,   # column number for label
                   data = train_h2o, # data in H2O format
                   activation = "RectifierWithDropout", # algorithm
                   input_dropout_ratio = 0.2, # % of inputs dropout
                   hidden_dropout_ratios = c(0.5,0.5), # % for nodes dropout
                   balance_classes = TRUE, 
                   hidden = c(100,100), # two layers of 100 nodes
                   momentum_stable = 0.99,
                   nesterov_accelerated_gradient = T, # use it for speed
                   epochs = 10) # max. no. of epochs
```

P.S.
The link to R Docker image has a trailing ")" and, therefore, is broken.

![untitled](https://cloud.githubusercontent.com/assets/4805827/11074214/6e7c751a-87bc-11e5-8571-d6ecaf0b1af3.png)

**Comment by KobaKhit** [comment]
There is no issue. h2o was in the process of migrating to a new release 3.0.3.6 and they haven't updated their CRAN docs and package. If interested [here](https://www.kaggle.com/kobakhit/digit-recognizer/digital-recognizer-in-r) is a working example of using h2o in R.

**Comment by nerdcha** [comment]
@KobaKhit Thanks for raising this, and sorry for the tardy response! We've fixed the typo in the URL—great catch! Just to confirm, the h2o integration is OK from our side, or is there more we should do?

**Comment by KobaKhit** [comment]
`h2o` works great. The problem was that I was using documentation for an old `h2o` release. They are developing really quickly, so it is a good idea to  keep an eye on their latest stable releases [here](http://h2o.ai/download/)

**Comment by nerdcha** [comment]
Cool, ok, thanks! I'll close the issue then.
