### ISSUE TITLE
Problem with Rmd script

### ISSUE THREAD

**Issue by matsavage** [Kaggle/docker-rstats#4]
I am having a problem with the following block of code when running an Rmd script;

```{r Auto ARIMA (NH), echo = FALSE, message = F, warning = F,  include = T, fig.align = 'center', fig.height=5, fig.width=8}
fit <- auto.arima(northts, lambda=0, d=0, D=1, max.order=4,
                  stepwise=FALSE, approximation=FALSE)
autoplot(forecast(fit, h = 36)) + xlim(2010, 2018) 
```

Executing this results in a 'unsupported character in output path' error, and seems to only arise fro plotting the figure, which is strange as ggplot seems to be supported well everywhere else, and I get the same error just using the basic 'plot(forecast(fit, h = 36)) + xlim(2010, 2018)' too.

[The Rmd file in question can be found here](https://www.kaggle.com/mathewsavage/d/nsidcorg/daily-sea-ice-extent-data/prediction-with-seasonal-arima)

**Comment by nerdcha** [comment]
Hi Mat, it seems that the Rmd renderer (or maybe ggplot) wants to save the plots as pngs with filenames based on the names of the Rmd code chunks that they're in. So the issue in this case was the brackets in `Auto ARIMA (NH)-1.png`. Sorry that wasn't clear! We'll see about improving the feedback in this type of case.

**Comment by matsavage** [comment]
Ah, thanks a lot! I thought it was a problem with `autoplot`, and completely overlooked the Rmd titles. I'll keep this in mind!
