### ISSUE TITLE
RStudio Server starts with R 3.1.1 by default

### ISSUE THREAD

**Issue by aakansh9** [Kaggle/docker-rstats#6]
```
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          1.1                         
year           2014                        
month          07                          
day            10                          
svn rev        66115                       
language       R                           
version.string R version 3.1.1 (2014-07-10)
nickname       Sock it to Me
```

Should be upgraded to latest version.

**Comment by nerdcha** [comment]
Thanks for reporting this. We've been building this on top of `rocker/hadleyverse`, which ultimately goes back to `rocker/verse`. Looking at their [build logs](https://hub.docker.com/r/rocker/verse/builds/), it looks like they've been flitting back and forth between 3.3.1 and 3.3.2 for a while. Has this been causing problems for you? (Having more dependable docker image builds is on our roadmap, but if it's a big problem then I can look at hacking something together faster for you.)

**Comment by aakansh9** [comment]
I was trying to import package `openxlsx` when I found that it supports > 3.3.0 only. Anyways, I solved it by adding `rsession-which-r=/usr/local/bin/R` to `/etc/rstudio/rserver.conf`. Maybe you can add that to the Dockerfile.

**Comment by nerdcha** [comment]
No problem! We've added this in https://github.com/Kaggle/docker-rstats/commit/b621e35a92b8c51bb8ed8e888b081b2c1ccbc29c and will deploy it shortly.
