### ISSUE TITLE
Error: Python module h2o4gpu was not found.

### ISSUE THREAD

**Issue by ismailmuller** [Kaggle/docker-rstats#68]
Hi there.

Using h2o4gpu package (which comes already installed in the image ) it gives the following error.
`Error: Python module h2o4gpu was not found.`

Thanks a lot for the very useful Docker image +++

```
library(h2o4gpu)
x <- iris[1:4]
y <- as.integer(iris$Species)
model <- h2o4gpu.random_forest_classifier() %>% fit(x, y)
```

**Comment by Philmod** [comment]
Hey @ismailmuller, I tried but I don't see this error: https://www.kaggle.com/philmod/kernel3865a9e732?scriptVersionId=13576755

Did you enable GPU?

**Comment by ismailmuller** [comment]
@Philmod I can't open the link.
Yes I enabled GPU.
https://www.kaggle.com/mullerismail/kernel1378499468

If you run the chunk twice you'll get the ` Error: Python module h2o4gpu was not found.`

**Comment by Philmod** [comment]
Hi @ismailmuller,

I'm very sorry I lost track of this bug. 

I cannot see your notebook, could you share it with me?
