### ISSUE TITLE
Request for adding TDA package to Kaggle Kernel

### ISSUE THREAD

**Issue by jclchan** [Kaggle/docker-rstats#72]
I'm new to Kaggle, so I'm not sure if here is the right place to submit requests for adding new R packages to Kaggle Kernel.  Sorry if I have submitted it in the wrong place.

The package I would like to be included is: 
https://cran.r-project.org/web/packages/TDA/index.html

Thanks a lot!

**Comment by djherbis** [comment]
@jclchan To my knowledge we periodically install/update all packages found here http://ftp.osuosl.org/pub/cran/web/packages/available_packages_by_date.html I see TDA in that list, can you confirm TDA is not installed and we can look into that deeper?

**Comment by jclchan** [comment]
Dear Dustin,

I tried to load the TDA library but failed:

Error in library("TDA"): there is no package called ‘TDA’
Traceback:

1. library("TDA")

I further checked the library installed in kernel, say those R packages
with 'T', but it does not list TDA. It seems that it is not there. I found
TDAstats, but no TDA.

Can we add TDA also?  Thanks!

**Comment by djherbis** [comment]
@jclchan It's likely that it's currently in our install sequence but we skip packages which fail due to missing dependencies or incompatibilities.

It may take some time to review why this particular package is being skipped.

**Comment by Philmod** [comment]
Have you tried installing the package on your notebook? `install.packages('TDA')`
