### ISSUE TITLE
Keras is not working in the last image

### ISSUE THREAD

**Issue by agenlu** [Kaggle/docker-rstats#81]
As you can see in this kernel:

https://www.kaggle.com/agenlu/keras-not-working

Keras has stopped to work on Kaggler R Kernels.

**Comment by Philmod** [comment]
Is it possible you forgot to specify some arguments?

![Screen Shot 2020-04-23 at 1 07 07 PM](https://user-images.githubusercontent.com/818310/80128252-615d9180-8563-11ea-93ee-0031702d8728.png)
