### ISSUE TITLE
Installation of R Pkg- ‘gifski’ and ‘ggalluvial’

### ISSUE THREAD

**Issue by Bang2018** [Kaggle/docker-rstats#85]
Hi,
        I am sharing my Kaggle Profile. Please install "gifski" and "ggalluvial". From my account I can install above two packages and run my code. In each session I am supposed to do the same to compile my code. After sharing the error free code to public mode I am getting error regarding the loading of packages. 
https://www.kaggle.com/krishm/nfl-1st-and-future-analytics-simulation
Your early reply is highly appreciated.

Thanks

**Comment by Philmod** [comment]
It seems like the package has a dependency on `cargo`. Here is a notebook installing these 2 packages: https://www.kaggle.com/gphilmod/install-gifski-and-ggalluvial?scriptVersionId=40281069
