### ISSUE TITLE
Cannot open parquet files

### ISSUE THREAD

**Issue by jmartindelasierra** [Kaggle/docker-rstats#87]
I cannot open parquet files. Loading reticulate package and importing pandas to access read_parquet() function doesn't work:

`library(reticulate)`
`pandas <- import("pandas")`

`Error in py_module_import(module, convert = convert): ImportError: No module named pandas`

If I configure the environment as follows

`Sys.setenv(RETICULATE_PYTHON="/opt/conda/envs/py36/bin/python3.6", required=TRUE)`

the import is successful, but the call to the read_parquet function results in a new error:

`mydata <- pandas$read_parquet("mydata.parquet")`

`Error in py_call_impl(callable, dots$args, dots$keywords): ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
pyarrow or fastparquet is required for parquet support`

I would need support to open parquet files with reticulate or by other means in my R notebooks at Kaggle.

Thank you

**Comment by jmartindelasierra** [comment]
Or please install a functional version of arrow package.

**Comment by Philmod** [comment]
The pandas setup has been fixed.

![Screen Shot 2020-08-06 at 1 37 25 PM](https://user-images.githubusercontent.com/818310/89563832-130a9080-d7ea-11ea-963e-ee8308f3e387.png)

Please reopen if you have any issue.
