### ISSUE TITLE
Request for R packages fable and forecastLM

### ISSUE THREAD

**Issue by davidjayjackson** [Kaggle/docker-rstats#90]
I would appreciate it if you would install fable and forecastLM packages. Thanks in advance.

**Comment by Philmod** [comment]
Feel free to create a PR, please include a unit test for each package.

**Comment by Philmod** [comment]
Actually, `fable` is installed in the base image. I added a test to make sure it will be installed in future builds. https://github.com/Kaggle/docker-rcran/pull/21

Unfortunately the [`forecastLM` package](https://github.com/RamiKrispin/forecastLM) doesn't meet our requirements to be added to the image. Feel free to install it in your kernel.
